"use strict";

const NodeMDA = require("nodemda");
const pluralize = require('pluralize');
const _ = require('lodash');
const OmniSchema = require('omni-schema');
const camelToWords = require('../_helpers/camelToWords');

/*
 * EntitySupport.js
 * Contains code that applies to the Entity class types generated by this
 * koa-react plugin.
 */
var EntitySupport = {};

(function() {

	EntitySupport.initStereotype = function(context, stereotype) {

		let model = context.model;

		model.mixin({

			onAttribute: [ 
			   { get: [

					function mantineInputTag() {
						if (this.isArray && this.type.isEnum) {
							return 'MultiSelect';
						}
						else {
						   return this.type.mantineInputTag;
						}
					},

				   function mantineDataLabel() {
						return camelToWords(this.name);
				   },

				   function mantineValueSuffix() {
						if (this.type.name == 'YesNo') {
							return ' ? "Yes" : "No"';
						}
						else if (this.type.name == 'OnOff') {
							return ' ? "On" : "Off"';
						}
						return '';
				   },


				   function mantineDefaultValue() {
						if (this.type.name == 'YesNo') {
							return this.defaultValue ? "'Yes'" : "'No'";
						}
						else if (this.type.name == 'OnOff') {
							return this.defaultValue ? "'On'" : "'Off'";
						}

						return this.jsDefaultValue;
				   },

				   function visibleToForm() {
					  return this.isPublic && !this.isTaggedAs('uiExclude');
				   },

				   function visibleToTable() {
					  return this.isTaggedAs('uiTableColumn');
				   },

				   function useArrayEditor() {
					   return this.isArray && !this.type.isEnum;
				   }
				]},

			],

			onClass: { 
				get: [
					/**
					* Returns a list of all attributes should be included
					* on any input forms generated for this class.
					*/ 
					function formAttribs() {
						let attribs = [];

						this.attributes.forEach(function (attrib) {
							if (attrib.visibleToForm) {
								attribs.push(attrib);
							}
						});

						this.virtuals.forEach(function (attrib) {
							if (attrib.visibleToForm) {
								attribs.push(attrib);
							}
						});

						return attribs;
					},

					/**
					* Returns a list of all attributes should be included
					* on any table generated for this class.
					*/
					function tableAttribs() {
						let attribs = [];

						this.attributes.forEach(function (attrib) {
							if (attrib.visibleToTable) {
								attribs.push(attrib);
							}
						});

						return attribs;
					},

					/**
					 * Returns a string to be passed to the select() method of a
					 * Mongoose query when retrieving a group of records in the getAllXX()
					 * REST handler.  null is returned if no query is needed.
					 */
					function mongooseSelect() {
						if (this.tableColumnsInvisible > 0) {
							// We need to select a subset of columns...
							let columns = [];
							if (this.tableColumnsVisible <= this.tableColumnsInvisible) {
								// Be explicit about which columns to include...
								columns.push('_id');
								this.attributes.forEach(function (attrib) {
									if (attrib.visibleToTable) {
										columns.push(attrib.jsIdentifierName);
									}
								});
							}
							else {

								// Be explicit about which columns to exclude...
								this.attributes.forEach(function (attrib) {
									if (!attrib.visibleToTable) {
										columns.push(`-${attrib.jsIdentifierName}`);
									}
								});
							}

							return `'${columns.join(' ')}'`;
						}
						return null;
					}
				] 
			},

		}); // end mixin

		// Make sure there are attributes in each Entity class that are tagged as
		// "uiTableColumn".  If NO attributes have the explicit tag, then ALL
		// attributes get the tag.
		model.classes.forEach(function (metaClass) {
			if (metaClass.stereotypeName === 'Entity') {

				// Count the visibleToTable attributes
				let visibleCount = 0;
				let invisibleCount = 0;
				metaClass.attributes.forEach(function (attrib) {
					if (attrib.visibleToTable) {
						visibleCount++;
					}
					else {
						invisibleCount++;
					}
				});

				// If there are NO explicit visibleToTable attributes, then
				// default to ALL primative types with multiplicity of 1 that
				// are visibleToForm
				if (visibleCount === 0) {
					invisibleCount = 0;
					metaClass.attributes.forEach(function (attrib) {
						if (attrib.visibleToForm && !attrib.isMany && !attrib.isObject) {
							attrib.addTag(new NodeMDA.Meta.Tag("uiTableColumn", true));
							visibleCount++;
						}
						else {
							invisibleCount++;
						}
					});
				}

				metaClass.tableColumnsVisible = visibleCount;
				metaClass.tableColumnsInvisible = invisibleCount;
			}
		});

	};

	
})();

module.exports = EntitySupport;
